replicaCount: 1

image:
  repository: networkcloud01/mongodb
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

auth:
  username: markone
  password: markone123
  database: markonedb
  rootPassword: admin123

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
