replicaCount: 1

image:
  repository: networkcloud01/task-management-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  REACT_APP_API_URL: "http://localhost:8000"
